config/routes.rb
Rails.application.routes.draw do

  get 'voice' => 'pages#vapi'
  
  root to: 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :event_urls
  resources :nccos
  resources :ncco_input_actions
  resources :ncco_stream_actions
  resources :ncco_talk_actions
  resources :ncco_connect_actions
  resources :ncco_record_actions
  resources :ncco_conversation_actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_url.rb
class EventUrl < ApplicationRecord
 include AlgoliaSearch

  algoliasearch do
    searchableAttributes ['uuid', 'conversation_uuid', 'email']
  end

end

app/models/ncco.rb
class Ncco < ApplicationRecord
end

app/models/ncco_connect_action.rb
class NccoConnectAction < ApplicationRecord
end

app/models/ncco_conversation_action.rb
class NccoConversationAction < ApplicationRecord
end

app/models/ncco_input_action.rb
class NccoInputAction < ApplicationRecord
end

app/models/ncco_record_action.rb
class NccoRecordAction < ApplicationRecord
end

app/models/ncco_stream_action.rb
class NccoStreamAction < ApplicationRecord
end

app/models/ncco_talk_action.rb
class NccoTalkAction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_action :authenticate_admin!
end

app/controllers/event_urls_controller.rb
class EventUrlsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:new, :create]

  before_action :set_event_url, only: [:show, :edit, :update, :destroy]

  # GET /event_urls
  # GET /event_urls.json
  def index
    if params[:search]
        @event_urls = EventUrl.order(created_at: :desc)
    else
        @event_urls = EventUrl.order(created_at: :desc)
    end
  end

  # GET /event_urls/1
  # GET /event_urls/1.json
  def show
  end

  # GET /event_urls/new
  def new
    @event_url = EventUrl.new
  end

  # GET /event_urls/1/edit
  def edit
  end

  # POST /event_urls
  # POST /event_urls.json
  def create
    @event_url = EventUrl.new(event_url_params)

    respond_to do |format|
      if @event_url.save
        format.html { redirect_to @event_url, notice: 'Event url was successfully created.' }
        format.json { render :show, status: :created, location: @event_url }
      else
        format.html { render :new }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_urls/1
  # PATCH/PUT /event_urls/1.json
  def update
    respond_to do |format|
      if @event_url.update(event_url_params)
        format.html { redirect_to @event_url, notice: 'Event url was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_url }
      else
        format.html { render :edit }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_urls/1
  # DELETE /event_urls/1.json
  def destroy
    @event_url.destroy
    respond_to do |format|
      format.html { redirect_to event_urls_url, notice: 'Event url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_url
      @event_url = EventUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_url_params
      params.permit(:start_time, :rate, :to, :from, :uuid, :conversation_uuid, :status, :direction, :recording_url, :rate, :start_time, :network, :price, :duration, :end_time, :search, :dtmf)
    end
end

app/controllers/nccos_controller.rb
class NccosController < ApplicationController
  before_action :set_ncco, only: [:show, :edit, :update, :destroy]

  # GET /nccos
  # GET /nccos.json
  def index
    @nccos = Ncco.all
  end

  # GET /nccos/1
  # GET /nccos/1.json
  def show
  end

  # GET /nccos/new
  def new
    @ncco = Ncco.new
  end

  # GET /nccos/1/edit
  def edit
  end

  # POST /nccos
  # POST /nccos.json
  def create
    @ncco = Ncco.new(ncco_params)

    respond_to do |format|
      if @ncco.save
        format.html { redirect_to @ncco, notice: 'Ncco was successfully created.' }
        format.json { render :show, status: :created, location: @ncco }
      else
        format.html { render :new }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nccos/1
  # PATCH/PUT /nccos/1.json
  def update
    respond_to do |format|
      if @ncco.update(ncco_params)
        format.html { redirect_to @ncco, notice: 'Ncco was successfully updated.' }
        format.json { render :show, status: :ok, location: @ncco }
      else
        format.html { render :edit }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nccos/1
  # DELETE /nccos/1.json
  def destroy
    @ncco.destroy
    respond_to do |format|
      format.html { redirect_to nccos_url, notice: 'Ncco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncco
      @ncco = Ncco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ncco_params
      params.fetch(:ncco, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def vapi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_urls_helper.rb
module EventUrlsHelper
end

app/helpers/ncco_connect_actions_helper.rb
module NccoConnectActionsHelper
end

app/helpers/ncco_input_actions_helper.rb
module NccoInputActionsHelper
end

app/helpers/ncco_record_actions_helper.rb
module NccoRecordActionsHelper
end

app/helpers/ncco_stream_actions_helper.rb
module NccoStreamActionsHelper
end

app/helpers/ncco_talk_actions_helper.rb
module NccoTalkActionsHelper
end

app/helpers/nccos_helper.rb
module NccosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/event_urls/_form.html.erb
<%= form_for(event_url) do |f| %>
  <% if event_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_url.errors.count, "error") %> prohibited this event_url from being saved:</h2>

      <ul>
      <% event_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :uuid, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :uuid, :class => 'form-control' %>
    </div>
    <%=f.error_span(:uuid) %>
  </div>

  <div class="form-group">
    <%= f.label :conversation_uuid, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :conversation_uuid, :class => 'form-control' %>
    </div>
    <%=f.error_span(:conversation_uuid) %>
  </div>

  <div class="form-group">
    <%= f.label :to, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :to, :class => 'form-control' %>
    </div>
    <%=f.error_span(:to) %>
  </div>

  <div class="form-group">
    <%= f.label :from, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :from, :class => 'form-control' %>
    </div>
    <%=f.error_span(:from) %>
  </div>

  <div class="form-group">
    <%= f.label :direction, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :direction, :class => 'form-control' %>
    </div>
    <%=f.error_span(:direction) %>
  </div>

  <div class="form-group">
    <%= f.label :recording_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :recording_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:recording_url) %>
  </div>

  <div class="form-group">
    <%= f.label :rate, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :rate, :class => 'form-control' %>
    </div>
    <%=f.error_span(:rate) %>
  </div>

  <div class="form-group">
    <%= f.label :start_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :start_time, :class => 'form-control' %>
    </div>
    <%=f.error_span(:start_time) %>
  </div>

  <br>

  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :status, :class => 'form-control' %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <br>

  <div class="form-group">
    <%= f.label :dtmf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dtmf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dtmf) %>
  </div>

  <br>

  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

   <br>

  <div class="form-group">
    <%= f.label :duration, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :duration, :class => 'form-control' %>
    </div>
    <%=f.error_span(:duration) %>
  </div>

   <br>

  <div class="form-group">
    <%= f.label :end_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :end_time, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_time) %>
  </div>

   <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_urls/edit.html.erb
<h1>Editing Event Url</h1>

<%= render 'form', event_url: @event_url %>

<%= link_to 'Show', @event_url %> |
<%= link_to 'Back', event_urls_path %>

app/views/event_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Urls</h1>

<table class="table table-striped">
  <thead>
    <tr>
        <th>uuid</th>
        <th>conversation_uuid</th>
        <th>to</th>
        <th>from</th>
        <th>direction</th>
        <th>recording_url</th>
        <th>rate</th>
        <th>start_time</th>
        <th>network</th>
        <th>dtmf</th>
        <th>status</th>
        <th>price</th>
        <th>duration</th>
        <th>end_time</th>
    </tr>
  </thead>

  <tbody>
    <% @event_urls.each do |event_url| %>
      <tr>
        <td><%= event_url.uuid %></td>
        <td><%= event_url.conversation_uuid %></td>
        <td><%= event_url.to %></td>
        <td><%= event_url.from %></td>
        <td><%= event_url.direction %></td>
        <td><%= event_url.recording_url %></td>
        <td><%= event_url.rate %></td>
        <td><%= event_url.start_time %></td>
        <td><%= event_url.network %></td>
        <td><%= event_url.dtmf %></td>
        <td><%= event_url.status %></td>
        <td><%= event_url.price %></td>
        <td><%= event_url.duration %></td>
        <td><%= event_url.end_time %></td>

        <td><%= link_to 'Show', event_url %></td>
        <td><%= link_to 'Edit', edit_event_url_path(event_url) %></td>
        <td><%= link_to 'Destroy', event_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Url', new_event_url_path %>

app/views/event_urls/new.html.erb
<h1>New Event Url</h1>

<%= render 'form', event_url: @event_url %>

<%= link_to 'Back', event_urls_path %>

app/views/event_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid</strong>
  <%= @event_url.uuid %>
</p>

<p>
  <strong>conversation_uuid</strong>
  <%= @event_url.conversation_uuid %>
</p>

<p>
  <strong>to</strong>
  <%= @event_url.to %>
</p>

<p>
  <strong>from</strong>
  <%= @event_url.from %>
</p>

<p>
  <strong>direction</strong>
  <%= @event_url.direction %>
</p>

<p>
  <strong>recording_url</strong>
  <%= @event_url.recording_url %>
</p>

<p>
  <strong>rate</strong>
  <%= @event_url.rate %>
</p>

<p>
  <strong>start_time</strong>
  <%= @event_url.start_time %>
</p>

<p>
  <strong>network</strong>
  <%= @event_url.network %>
</p>

<p>
  <strong>dtmf</strong>
  <%= @event_url.dtmf %>
</p>

<p>
  <strong>status</strong>
  <%= @event_url.status %>
</p>

<p>
  <strong>price</strong>
  <%= @event_url.price %>
</p>

<p>
  <strong>duration</strong>
  <%= @event_url.duration %>
</p>

<p>
  <strong>end_time</strong>
  <%= @event_url.end_time %>
</p>

<%= link_to 'Edit', edit_event_url_path(@event_url) %> |
<%= link_to 'Back', event_urls_path %>

app/views/nccos/_form.html.erb
<%= form_for @ncco, :html => { :class => "form-horizontal ncco" } do |f| %>

  <% if @ncco.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@ncco.errors.count, "error") %> prohibited this ncco from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @ncco.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                nccos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/nccos/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a><%= link_to "Home", root_path, :class => "navbar-brand" %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">NCCO actions<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">

            <li class="divider"></li>
            <li><%= link_to "NCCO - Conversation", ncco_conversation_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Input", ncco_input_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Stream", ncco_stream_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Talk", ncco_talk_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Connect", ncco_connect_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Record", ncco_record_actions_path %></li>
            <li class="divider"></li>
            <li><%= link_to "NCCO - Conversation", ncco_conversation_actions_path %></li>
            <li class="divider"></li>

          </ul>

          <li><%= link_to "Event URLs", event_urls_path %></li>
          <li class="divider"></li>

        </li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%= form_tag(event_urls_path || nccos_path, :method => 'get') do %>
        </div><%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control"  %><%= submit_tag "Search", :name => nil, :class => "btn btn-default" %><% end %>
      </form>


      <ul class="nav navbar-nav navbar-right">
        <li><a href="https://addons-sso.heroku.com/apps/3c8ad263-31da-4ebc-9d3f-c7aaa3283dc3/addons/2276b2d3-f474-45d7-b066-70fafd616308">Logs</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/nccos/edit.html.erb
<%- model_class = Ncco -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nccos/index.html.erb
<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#record" aria-controls="record" role="tab" data-toggle="tab">Record</a></li>
    <li role="presentation"><a href="#conversation" aria-controls="conversation" role="tab" data-toggle="tab">Conversation</a></li>
    <li role="presentation"><a href="#connect" aria-controls="connect" role="tab" data-toggle="tab">Connect</a></li>
    <li role="presentation"><a href="#talk" aria-controls="talk" role="tab" data-toggle="tab">Talk</a></li>
    <li role="presentation"><a href="#stream" aria-controls="stream" role="tab" data-toggle="tab">Stream</a></li>
    <li role="presentation"><a href="#input" aria-controls="input" role="tab" data-toggle="tab">Input</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="record">Use the record action to record a Call or part of a Call: The record action is asynchronous. Recording starts when the record action is executed in the NCCO and finishes when the synchronous condition in the action is met. That is, endOnSilence, timeOut or endOnKey. If you do not set a synchronous condition, the Voice API immediately executes the next NCCO without recording.

For information about the workflow to follow, see Recordings.</div>
    <div role="tabpanel" class="tab-pane" id="conversation">You can use the conversation action to create standard or moderated Conversations. The first person to call the virtual number assigned to the Conversation creates it. This action is synchronous, the Conversation lasts until the number of participants is 0.

    Note: you can invite up to 50 people to your Conversation.
</div>
    <div role="tabpanel" class="tab-pane" id="connect">You can use the connect action to connect a call to endpoints such as phone numbers.

This action is synchronous, after a connect the next action in the NCCO stack is processed. A connect action ends when the endpoint you are calling is busy or unavailable. You ring endpoints sequentially by nesting connect actions.</div>
    <div role="tabpanel" class="tab-pane" id="talk">The talk action sends synthesized speech to a Conversation.

The text provided in the talk action can either be plain, or formatted using SSML. SSML tags provide further instructions to the text-to-speech synthesiser which allow you to set pitch, pronunciation and to combine together text in multiple languages. SSML tags are XML-based and sent inline in the JSON string.

By default, the talk action is synchronous. However, if you set bargeIn to true you must set an input action later in the NCCO stack. </div>
    <div role="tabpanel" class="tab-pane" id="stream">The stream action allows you to send an audio stream to a Conversation

By default, the talk action is synchronous. However, if you set bargeIn to true you must set an input action later in the NCCO stack. </div>
    <div role="tabpanel" class="tab-pane" id="input">You can use the input action to collect digits input by the person you are calling. This action is synchronous, Nexmo processes the input and forwards it in the parameters sent to the eventURL webhook endpoint you configure in your request. Your webhook endpoint should return another NCCO that replaces the existing NCCO and controls the Call based on the user input. You could use this functionality to create an Interactive Voice Response (IVR). For example, if your user presses 4, you return a connect NCCO that forwards the call to your sales department.</div>
  </div>

</div>

app/views/nccos/new.html.erb
<%- model_class = Ncco -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nccos/show.html.erb
<%- model_class = Ncco -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              nccos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ncco_path(@ncco), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ncco_path(@ncco),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>