config/routes.rb
Rails.application.routes.draw do

  get 'voice' => 'pages#vapi'
  
  root to: 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :event_urls
  resources :nccos
  resources :ncco_input_actions
  resources :ncco_stream_actions
  resources :ncco_talk_actions
  resources :ncco_connect_actions
  resources :ncco_record_actions
  resources :ncco_conversation_actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_url.rb
class EventUrl < ApplicationRecord
 include AlgoliaSearch

  algoliasearch do
    searchableAttributes ['uuid', 'conversation_uuid', 'email']
  end

end

app/models/ncco.rb
class Ncco < ApplicationRecord
end

app/models/ncco_connect_action.rb
class NccoConnectAction < ApplicationRecord
end

app/models/ncco_conversation_action.rb
class NccoConversationAction < ApplicationRecord
end

app/models/ncco_input_action.rb
class NccoInputAction < ApplicationRecord
end

app/models/ncco_record_action.rb
class NccoRecordAction < ApplicationRecord
end

app/models/ncco_stream_action.rb
class NccoStreamAction < ApplicationRecord
end

app/models/ncco_talk_action.rb
class NccoTalkAction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_action :authenticate_admin!
end

app/controllers/event_urls_controller.rb
class EventUrlsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:new, :create]

  before_action :set_event_url, only: [:show, :edit, :update, :destroy]

  # GET /event_urls
  # GET /event_urls.json
  def index
    if params[:search]
        @event_urls = EventUrl.order(created_at: :desc)
    else
        @event_urls = EventUrl.order(created_at: :desc)
    end
  end

  # GET /event_urls/1
  # GET /event_urls/1.json
  def show
  end

  # GET /event_urls/new
  def new
    @event_url = EventUrl.new
  end

  # GET /event_urls/1/edit
  def edit
  end

  # POST /event_urls
  # POST /event_urls.json
  def create
    @event_url = EventUrl.new(event_url_params)

    respond_to do |format|
      if @event_url.save
        format.html { redirect_to @event_url, notice: 'Event url was successfully created.' }
        format.json { render :show, status: :created, location: @event_url }
      else
        format.html { render :new }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_urls/1
  # PATCH/PUT /event_urls/1.json
  def update
    respond_to do |format|
      if @event_url.update(event_url_params)
        format.html { redirect_to @event_url, notice: 'Event url was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_url }
      else
        format.html { render :edit }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_urls/1
  # DELETE /event_urls/1.json
  def destroy
    @event_url.destroy
    respond_to do |format|
      format.html { redirect_to event_urls_url, notice: 'Event url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_url
      @event_url = EventUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_url_params
      params.permit(:start_time, :rate, :to, :from, :uuid, :conversation_uuid, :status, :direction, :recording_url, :rate, :start_time, :network, :price, :duration, :end_time, :search, :dtmf)
    end
end

app/controllers/ncco_stream_actions_controller.rb
class NccoStreamActionsController < ApplicationController
  before_action :set_ncco_stream_action, only: [:show, :edit, :update, :destroy]

  # GET /ncco_stream_actions
  # GET /ncco_stream_actions.json
  def index
    @ncco_stream_actions = NccoStreamAction.all
  end

  # GET /ncco_stream_actions/1
  # GET /ncco_stream_actions/1.json
  def show
  end

  # GET /ncco_stream_actions/new
  def new
    @ncco_stream_action = NccoStreamAction.new
  end

  # GET /ncco_stream_actions/1/edit
  def edit
  end

  # POST /ncco_stream_actions
  # POST /ncco_stream_actions.json
  def create
    @ncco_stream_action = NccoStreamAction.new(ncco_stream_action_params)

    respond_to do |format|
      if @ncco_stream_action.save
        format.html { redirect_to @ncco_stream_action, notice: 'Ncco stream action was successfully created.' }
        format.json { render :show, status: :created, location: @ncco_stream_action }
      else
        format.html { render :new }
        format.json { render json: @ncco_stream_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ncco_stream_actions/1
  # PATCH/PUT /ncco_stream_actions/1.json
  def update
    respond_to do |format|
      if @ncco_stream_action.update(ncco_stream_action_params)
        format.html { redirect_to @ncco_stream_action, notice: 'Ncco stream action was successfully updated.' }
        format.json { render :show, status: :ok, location: @ncco_stream_action }
      else
        format.html { render :edit }
        format.json { render json: @ncco_stream_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ncco_stream_actions/1
  # DELETE /ncco_stream_actions/1.json
  def destroy
    @ncco_stream_action.destroy
    respond_to do |format|
      format.html { redirect_to ncco_stream_actions_url, notice: 'Ncco stream action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncco_stream_action
      @ncco_stream_action = NccoStreamAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ncco_stream_action_params
      params.require(:ncco_stream_action).permit(:stream_url, :loop)
    end
end

app/controllers/nccos_controller.rb
class NccosController < ApplicationController
  before_action :set_ncco, only: [:show, :edit, :update, :destroy]

  # GET /nccos
  # GET /nccos.json
  def index
    @nccos = Ncco.all
  end

  # GET /nccos/1
  # GET /nccos/1.json
  def show
  end

  # GET /nccos/new
  def new
    @ncco = Ncco.new
  end

  # GET /nccos/1/edit
  def edit
  end

  # POST /nccos
  # POST /nccos.json
  def create
    @ncco = Ncco.new(ncco_params)

    respond_to do |format|
      if @ncco.save
        format.html { redirect_to @ncco, notice: 'Ncco was successfully created.' }
        format.json { render :show, status: :created, location: @ncco }
      else
        format.html { render :new }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nccos/1
  # PATCH/PUT /nccos/1.json
  def update
    respond_to do |format|
      if @ncco.update(ncco_params)
        format.html { redirect_to @ncco, notice: 'Ncco was successfully updated.' }
        format.json { render :show, status: :ok, location: @ncco }
      else
        format.html { render :edit }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nccos/1
  # DELETE /nccos/1.json
  def destroy
    @ncco.destroy
    respond_to do |format|
      format.html { redirect_to nccos_url, notice: 'Ncco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncco
      @ncco = Ncco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ncco_params
      params.fetch(:ncco, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def vapi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_urls_helper.rb
module EventUrlsHelper
end

app/helpers/ncco_input_actions_helper.rb
module NccoInputActionsHelper
end

app/helpers/ncco_stream_actions_helper.rb
module NccoStreamActionsHelper
end

app/helpers/ncco_talk_actions_helper.rb
module NccoTalkActionsHelper
end

app/helpers/nccos_helper.rb
module NccosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ncco_stream_actions/_form.html.erb
<%= form_for @ncco_stream_action, :html => { :class => "form-horizontal ncco_stream_action" } do |f| %>

  <% if @ncco_stream_action.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@ncco_stream_action.errors.count, "error") %> prohibited this ncco_stream_action from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @ncco_stream_action.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :stream_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :stream_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:stream_url) %>
  </div>
  <div class="form-group">
    <%= f.label :loop, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :loop, :class => 'form-control' %>
    </div>
    <%=f.error_span(:loop) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ncco_stream_actions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/ncco_stream_actions/edit.html.erb
<%- model_class = NccoStreamAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ncco_stream_actions/index.html.erb
<%- model_class = NccoStreamAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:stream_url) %></th>
      <th><%= model_class.human_attribute_name(:loop) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ncco_stream_actions.each do |ncco_stream_action| %>
      <tr>
        <td><%= link_to ncco_stream_action.id, ncco_stream_action_path(ncco_stream_action) %></td>
        <td><%= ncco_stream_action.stream_url %></td>
        <td><%= ncco_stream_action.loop %></td>
        <td><%=l ncco_stream_action.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ncco_stream_action_path(ncco_stream_action), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ncco_stream_action_path(ncco_stream_action),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ncco_stream_action_path,
            :class => 'btn btn-primary' %>

app/views/ncco_stream_actions/new.html.erb
<%- model_class = NccoStreamAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ncco_stream_actions/show.html.erb
<%- model_class = NccoStreamAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:stream_url) %>:</strong></dt>
  <dd><%= @ncco_stream_action.stream_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:loop) %>:</strong></dt>
  <dd><%= @ncco_stream_action.loop %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ncco_stream_actions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ncco_stream_action_path(@ncco_stream_action), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ncco_stream_action_path(@ncco_stream_action),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>