config/routes.rb
Rails.application.routes.draw do

  get 'voice' => 'pages#vapi'
  
  root to: 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :event_urls
  resources :nccos
  resources :ncco_input_actions
  resources :ncco_stream_actions
  resources :ncco_talk_actions
  resources :ncco_connect_actions
  resources :ncco_record_actions
  resources :ncco_conversation_actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/ncco_record_actions_controller.rb
class NccoRecordActionsController < ApplicationController
  before_action :set_ncco_record_action, only: [:show, :edit, :update, :destroy]

  # GET /ncco_record_actions
  # GET /ncco_record_actions.json
  def index
    @ncco_record_actions = NccoRecordAction.all
  end

  # GET /ncco_record_actions/1
  # GET /ncco_record_actions/1.json
  def show
  end

  # GET /ncco_record_actions/new
  def new
    @ncco_record_action = NccoRecordAction.new
  end

  # GET /ncco_record_actions/1/edit
  def edit
  end

  # POST /ncco_record_actions
  # POST /ncco_record_actions.json
  def create
    @ncco_record_action = NccoRecordAction.new(ncco_record_action_params)

    respond_to do |format|
      if @ncco_record_action.save
        format.html { redirect_to @ncco_record_action, notice: 'Ncco record action was successfully created.' }
        format.json { render :show, status: :created, location: @ncco_record_action }
      else
        format.html { render :new }
        format.json { render json: @ncco_record_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ncco_record_actions/1
  # PATCH/PUT /ncco_record_actions/1.json
  def update
    respond_to do |format|
      if @ncco_record_action.update(ncco_record_action_params)
        format.html { redirect_to @ncco_record_action, notice: 'Ncco record action was successfully updated.' }
        format.json { render :show, status: :ok, location: @ncco_record_action }
      else
        format.html { render :edit }
        format.json { render json: @ncco_record_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ncco_record_actions/1
  # DELETE /ncco_record_actions/1.json
  def destroy
    @ncco_record_action.destroy
    respond_to do |format|
      format.html { redirect_to ncco_record_actions_url, notice: 'Ncco record action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncco_record_action
      @ncco_record_action = NccoRecordAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ncco_record_action_params
      params.require(:ncco_record_action).permit(:format, :split, :start_on_answer, :end_on_key, :destination_url, :streamed, :limit, :validity_time, :event_url, :event_method, :backup_url, :backup_method, :beep_start, :beep_finish, :secure)
    end
end

app/helpers/ncco_record_actions_helper.rb
module NccoRecordActionsHelper
end

app/views/ncco_record_actions/_form.html.erb
<%= form_for @ncco_record_action, :html => { :class => "form-horizontal ncco_record_action" } do |f| %>

  <% if @ncco_record_action.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@ncco_record_action.errors.count, "error") %> prohibited this ncco_record_action from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @ncco_record_action.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :format, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :format, :class => 'form-control' %>
    </div>
    <%=f.error_span(:format) %>
  </div>
  <div class="form-group">
    <%= f.label :split, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :split, :class => 'form-control' %>
    </div>
    <%=f.error_span(:split) %>
  </div>
  <div class="form-group">
    <%= f.label :start_on_answer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :start_on_answer, :class => 'form-control' %>
    </div>
    <%=f.error_span(:start_on_answer) %>
  </div>
  <div class="form-group">
    <%= f.label :end_on_key, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :end_on_key, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_on_key) %>
  </div>
  <div class="form-group">
    <%= f.label :destination_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :destination_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:destination_url) %>
  </div>
  <div class="form-group">
    <%= f.label :streamed, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :streamed, :class => 'form-control' %>
    </div>
    <%=f.error_span(:streamed) %>
  </div>
  <div class="form-group">
    <%= f.label :limit, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :limit, :class => 'form-control' %>
    </div>
    <%=f.error_span(:limit) %>
  </div>
  <div class="form-group">
    <%= f.label :validity_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :validity_time, :class => 'form-control' %>
    </div>
    <%=f.error_span(:validity_time) %>
  </div>
  <div class="form-group">
    <%= f.label :event_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_url) %>
  </div>
  <div class="form-group">
    <%= f.label :event_method, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :event_method, :class => 'form-control' %>
    </div>
    <%=f.error_span(:event_method) %>
  </div>
  <div class="form-group">
    <%= f.label :backup_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :backup_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:backup_url) %>
  </div>
  <div class="form-group">
    <%= f.label :backup_method, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :backup_method, :class => 'form-control' %>
    </div>
    <%=f.error_span(:backup_method) %>
  </div>
  <div class="form-group">
    <%= f.label :beep_start, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :beep_start, :class => 'form-control' %>
    </div>
    <%=f.error_span(:beep_start) %>
  </div>
  <div class="form-group">
    <%= f.label :beep_finish, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :beep_finish, :class => 'form-control' %>
    </div>
    <%=f.error_span(:beep_finish) %>
  </div>
  <div class="form-group">
    <%= f.label :secure, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :secure, :class => 'form-control' %>
    </div>
    <%=f.error_span(:secure) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                ncco_record_actions_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/ncco_record_actions/edit.html.erb
<%- model_class = NccoRecordAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ncco_record_actions/index.html.erb
<%- model_class = NccoRecordAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:format) %></th>
      <th><%= model_class.human_attribute_name(:split) %></th>
      <th><%= model_class.human_attribute_name(:start_on_answer) %></th>
      <th><%= model_class.human_attribute_name(:end_on_key) %></th>
      <th><%= model_class.human_attribute_name(:destination_url) %></th>
      <th><%= model_class.human_attribute_name(:streamed) %></th>
      <th><%= model_class.human_attribute_name(:limit) %></th>
      <th><%= model_class.human_attribute_name(:validity_time) %></th>
      <th><%= model_class.human_attribute_name(:event_url) %></th>
      <th><%= model_class.human_attribute_name(:event_method) %></th>
      <th><%= model_class.human_attribute_name(:backup_url) %></th>
      <th><%= model_class.human_attribute_name(:backup_method) %></th>
      <th><%= model_class.human_attribute_name(:beep_start) %></th>
      <th><%= model_class.human_attribute_name(:beep_finish) %></th>
      <th><%= model_class.human_attribute_name(:secure) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ncco_record_actions.each do |ncco_record_action| %>
      <tr>
        <td><%= link_to ncco_record_action.id, ncco_record_action_path(ncco_record_action) %></td>
        <td><%= ncco_record_action.format %></td>
        <td><%= ncco_record_action.split %></td>
        <td><%= ncco_record_action.start_on_answer %></td>
        <td><%= ncco_record_action.end_on_key %></td>
        <td><%= ncco_record_action.destination_url %></td>
        <td><%= ncco_record_action.streamed %></td>
        <td><%= ncco_record_action.limit %></td>
        <td><%= ncco_record_action.validity_time %></td>
        <td><%= ncco_record_action.event_url %></td>
        <td><%= ncco_record_action.event_method %></td>
        <td><%= ncco_record_action.backup_url %></td>
        <td><%= ncco_record_action.backup_method %></td>
        <td><%= ncco_record_action.beep_start %></td>
        <td><%= ncco_record_action.beep_finish %></td>
        <td><%= ncco_record_action.secure %></td>
        <td><%=l ncco_record_action.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ncco_record_action_path(ncco_record_action), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ncco_record_action_path(ncco_record_action),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ncco_record_action_path,
            :class => 'btn btn-primary' %>

app/views/ncco_record_actions/new.html.erb
<%- model_class = NccoRecordAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ncco_record_actions/show.html.erb
<%- model_class = NccoRecordAction -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:format) %>:</strong></dt>
  <dd><%= @ncco_record_action.format %></dd>
  <dt><strong><%= model_class.human_attribute_name(:split) %>:</strong></dt>
  <dd><%= @ncco_record_action.split %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_on_answer) %>:</strong></dt>
  <dd><%= @ncco_record_action.start_on_answer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_on_key) %>:</strong></dt>
  <dd><%= @ncco_record_action.end_on_key %></dd>
  <dt><strong><%= model_class.human_attribute_name(:destination_url) %>:</strong></dt>
  <dd><%= @ncco_record_action.destination_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:streamed) %>:</strong></dt>
  <dd><%= @ncco_record_action.streamed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:limit) %>:</strong></dt>
  <dd><%= @ncco_record_action.limit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:validity_time) %>:</strong></dt>
  <dd><%= @ncco_record_action.validity_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_url) %>:</strong></dt>
  <dd><%= @ncco_record_action.event_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:event_method) %>:</strong></dt>
  <dd><%= @ncco_record_action.event_method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:backup_url) %>:</strong></dt>
  <dd><%= @ncco_record_action.backup_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:backup_method) %>:</strong></dt>
  <dd><%= @ncco_record_action.backup_method %></dd>
  <dt><strong><%= model_class.human_attribute_name(:beep_start) %>:</strong></dt>
  <dd><%= @ncco_record_action.beep_start %></dd>
  <dt><strong><%= model_class.human_attribute_name(:beep_finish) %>:</strong></dt>
  <dd><%= @ncco_record_action.beep_finish %></dd>
  <dt><strong><%= model_class.human_attribute_name(:secure) %>:</strong></dt>
  <dd><%= @ncco_record_action.secure %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ncco_record_actions_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ncco_record_action_path(@ncco_record_action), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ncco_record_action_path(@ncco_record_action),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>