config/routes.rb
Rails.application.routes.draw do

  get 'voice' => 'pages#vapi'
  
  root to: 'pages#index'

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :event_urls
  resources :nccos
  resources :ncco_input_actions
  resources :ncco_stream_actions
  resources :ncco_talk_actions
  resources :ncco_connect_actions
  resources :ncco_record_actions
  resources :ncco_conversation_actions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_url.rb
class EventUrl < ApplicationRecord
 include AlgoliaSearch

  algoliasearch do
    searchableAttributes ['uuid', 'conversation_uuid', 'email']
  end

end

app/models/ncco.rb
class Ncco < ApplicationRecord
end

app/models/ncco_connect_action.rb
class NccoConnectAction < ApplicationRecord
end

app/models/ncco_conversation_action.rb
class NccoConversationAction < ApplicationRecord
end

app/models/ncco_input_action.rb
class NccoInputAction < ApplicationRecord
end

app/models/ncco_record_action.rb
class NccoRecordAction < ApplicationRecord
end

app/models/ncco_stream_action.rb
class NccoStreamAction < ApplicationRecord
end

app/models/ncco_talk_action.rb
class NccoTalkAction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_action :authenticate_admin!
end

app/controllers/event_urls_controller.rb
class EventUrlsController < ApplicationController
  skip_before_action :authenticate_admin!, only: [:new, :create]

  before_action :set_event_url, only: [:show, :edit, :update, :destroy]

  # GET /event_urls
  # GET /event_urls.json
  def index
    if params[:search]
        @event_urls = EventUrl.order(created_at: :desc)
    else
        @event_urls = EventUrl.order(created_at: :desc)
    end
  end

  # GET /event_urls/1
  # GET /event_urls/1.json
  def show
  end

  # GET /event_urls/new
  def new
    @event_url = EventUrl.new
  end

  # GET /event_urls/1/edit
  def edit
  end

  # POST /event_urls
  # POST /event_urls.json
  def create
    @event_url = EventUrl.new(event_url_params)

    respond_to do |format|
      if @event_url.save
        format.html { redirect_to @event_url, notice: 'Event url was successfully created.' }
        format.json { render :show, status: :created, location: @event_url }
      else
        format.html { render :new }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_urls/1
  # PATCH/PUT /event_urls/1.json
  def update
    respond_to do |format|
      if @event_url.update(event_url_params)
        format.html { redirect_to @event_url, notice: 'Event url was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_url }
      else
        format.html { render :edit }
        format.json { render json: @event_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_urls/1
  # DELETE /event_urls/1.json
  def destroy
    @event_url.destroy
    respond_to do |format|
      format.html { redirect_to event_urls_url, notice: 'Event url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_url
      @event_url = EventUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_url_params
      params.permit(:start_time, :rate, :to, :from, :uuid, :conversation_uuid, :status, :direction, :recording_url, :rate, :start_time, :network, :price, :duration, :end_time, :search, :dtmf)
    end
end

app/controllers/nccos_controller.rb
class NccosController < ApplicationController
  before_action :set_ncco, only: [:show, :edit, :update, :destroy]

  # GET /nccos
  # GET /nccos.json
  def index
    @nccos = Ncco.all
  end

  # GET /nccos/1
  # GET /nccos/1.json
  def show
  end

  # GET /nccos/new
  def new
    @ncco = Ncco.new
  end

  # GET /nccos/1/edit
  def edit
  end

  # POST /nccos
  # POST /nccos.json
  def create
    @ncco = Ncco.new(ncco_params)

    respond_to do |format|
      if @ncco.save
        format.html { redirect_to @ncco, notice: 'Ncco was successfully created.' }
        format.json { render :show, status: :created, location: @ncco }
      else
        format.html { render :new }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nccos/1
  # PATCH/PUT /nccos/1.json
  def update
    respond_to do |format|
      if @ncco.update(ncco_params)
        format.html { redirect_to @ncco, notice: 'Ncco was successfully updated.' }
        format.json { render :show, status: :ok, location: @ncco }
      else
        format.html { render :edit }
        format.json { render json: @ncco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nccos/1
  # DELETE /nccos/1.json
  def destroy
    @ncco.destroy
    respond_to do |format|
      format.html { redirect_to nccos_url, notice: 'Ncco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ncco
      @ncco = Ncco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ncco_params
      params.fetch(:ncco, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def vapi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_urls_helper.rb
module EventUrlsHelper
end

app/helpers/ncco_input_actions_helper.rb
module NccoInputActionsHelper
end

app/helpers/ncco_talk_actions_helper.rb
module NccoTalkActionsHelper
end

app/helpers/nccos_helper.rb
module NccosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <a class="text-muted"><%= link_to "nexmo docs", "https://developer.nexmo.com/", target: :blank, :class => "navbar-brand" %></a>
          <a class="text-muted"><%= link_to "voice playground", "https://dashboard.nexmo.com/voice/playground", target: :blank, :class => "navbar-brand" %></a>
          <a class="text-muted"><%= link_to "nexmo-api app", "https://api-nexmo-v2.herokuapp.com/", target: :blank, :class => "navbar-brand" %></a>
        </div>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <% if current_admin %>
      <a><%= link_to "Home", root_path, :class => "navbar-brand" %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "Voice API",  voice_path, :class => "navbar-brand" %></li>
        <li>

                <li><%= link_to "Event URLs", event_urls_path, :class => "navbar-brand" %></li>
                <li class="divider"></li>
                <li><%= link_to "Dashboard", rails_admin_path, :class => "navbar-brand" %></li>
        </li>
      </ul>

      <%= render 'layouts/search' %>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Create an admin', new_admin_registration_path, :class => "navbar-brand"%></li>
        <li><%= link_to 'Logs', 'https://addons-sso.heroku.com/apps/3c8ad263-31da-4ebc-9d3f-c7aaa3283dc3/addons/2276b2d3-f474-45d7-b066-70fafd616308', target: :blank, :class => "navbar-brand" %></li>
        <li><%= link_to 'Log Out', destroy_admin_session_path, method: :delete, :class => "navbar-brand" %></li>
      </ul>

      <% else %>

          <a><%= link_to 'Log In', admin_session_path, :class => "navbar-brand" %></a>
      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%= form_tag(event_urls_path || nccos_path, :method => 'get') do %>
        </div><%= text_field_tag :search, params[:search], placeholder: "Search", :class => "form-control"  %><%= submit_tag "Search", :name => nil, :class => "btn btn-default" %><% end %>
      </form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conversations Callback App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery.min.js' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="bs-docs-header">
    <div class="container-fluid">
      <h1>Conversations Callbacks App</h1>
       <h3>Search and report on the data that Nexmo sends to your webhooks.</h3>
         <br>
    </div>
</div>

app/views/pages/vapi.html.erb
<h2>Some of Nexmo Voice API features:</h2>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingOne">
<h4 class="panel-title">
<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
 Powerful Call Control.
</a>
</h4>
</div>
<div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
<div class="panel-body">
Control the flow of your calls with a powerful set of call control features allowing complex voice use cases.    <%= link_to "Check the NCCO Reference", nccos_path %>
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingTwo">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
 Call Recording.
</a>
</h4>
</div>
<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
<div class="panel-body">
Record and store inbound or outbound (software-initiated) calls. Split-recording and dynamic contextual recording coming soon. <%= link_to "Create a NCCO record action", ncco_record_actions_path %>
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingThree">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
 Voice Conferencing.
</a>
</h4>
</div>
<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
<div class="panel-body">
Create a conference in one line of code. As simple as you want or with powerful enterprise features. <%= link_to "Create a NCCO - Conversation", ncco_conversation_actions_path %>
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingThree">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
 Speak your Customers’ Language.
</a>
</h4>
</div>
<div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
<div class="panel-body">
Nexmo offers a text to speech engine in over 23 languages in different genders and accents.
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingThree">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
 Inbound Call Processing.
</a>
</h4>
</div>
<div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
<div class="panel-body">
Manage inbound calls in developer-friendly JSON with Nexmo Call Control Objects.
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingSix">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
 Voice Proxy.
</a>
</h4>
</div>
<div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
<div class="panel-body">
Protect your customers’ identities by masking their phone numbers with a voice proxy solution.
</div>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading" role="tab" id="headingSeven">
<h4 class="panel-title">
<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
 Voice Menus (IVRs).
</a>
</h4>
</div>
<div id="collapseSeven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSeven">
<div class="panel-body">
Protect your customers’ identities by masking their phone numbers with a voice proxy solution.
</div>
</div>